apiVersion: apps/v1
kind: Deployment
metadata:
  name: shows-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shows
  template:
    metadata:
      labels:
        app: shows
    spec:
      containers:
        - name: shows
          image: wentaozhai/shows
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: MONGO_URI
              value: 'mongodb://shows-mongo-srv:27017/shows'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: shows-srv
spec:
  selector:
    app: shows
  ports:
    - name: shows
      protocol: TCP
      port: 3000
      targetPort: 3000